application:
  security:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  servlet:
    context-path: /api/v1/
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_demo_db_v_1?createDatabaseIfNotExist=true
    username: Youssef
    password: YOUSSEF02
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ana
    password: ana
    properties:
      mail:
        stmp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    protocole: smtp


